const cardExamples = [
  {
    name: "Borg Anderson",
    wish: "To go on a fishing trip with his dad",
    guardian: "David Anderson (Father)",
    contact: "555-234-5678",
    progress: 50,
  },
  {
    name: "Ariana Alvarez",
    wish: "To swim with dolphins",
    guardian: "Javier Alvarez (Father)",
    contact: "555-345-6789",
    progress: 75,
  },
  {
    name: "Sam Abbott",
    wish: "To go to New York City",
    guardian: "Stephanie Abbott (Mother)",
    contact: "555-456-7890",
    progress: 90,
  },
  {
    name: "Lily Allen",
    wish: "To meet a famous artist",
    guardian: "Melanie Allen (Mother)",
    contact: "555-123-4567",
    progress: 80,
  },
  {
    name: "Mia Brown",
    wish: "To visit Disney World",
    guardian: "Karen Brown (Mother)",
    contact: "555-123-4567",
    progress: 75,
  },
  {
    name: "Mason Baker",
    wish: "To go on a fishing trip",
    guardian: "David Baker (Father)",
    contact: "555-203-3333",
    progress: 40,
  },
  {
    name: "Liam Carter",
    wish: "To ride in a helicopter",
    guardian: "Kelly Carter (Mother)",
    contact: "555-123-4567",
    progress: 100,
  },
  {
    name: "Sophie Chen",
    wish: "To meet her favorite singer, Taylor Swift",
    guardian: "William Chen (Father)",
    contact: "555-555-1212",
    progress: 25,
  },
  {
    name: "Sophia Davis",
    wish: "To meet a famous actor",
    guardian: "David Davis (Father)",
    contact: "555-123-4567",
    progress: 75,
  },
  {
    name: "Davi Santos",
    wish: "To meet Neymar",
    guardian: "Neymar Santos (Father)",
    contact: "302-303-2035",
    progress: 100,
  },
  {
    name: "Miles Davis",
    wish: "To play the trumpet",
    guardian: "Sammy Davis (Brother)",
    contact: "203-303-3333",
    progress: 50,
  },
  {
    name: "Emily Green",

    wish: "To meet her favorite singer, Taylor Swift",
    guardian: "Karen Green (Mother)",
    contact: "555-987-6543",
    progress: 80,
  },
  {
    name: "Jacob Garcia",
    wish: "To go on a trip to Disney World",
    guardian: "Maria Garcia (Mother)",
    contact: "555-555-1212",
    progress: 100,
  },
  {
    name: "Olivia Grant",
    wish: "To have a room makeover",
    guardian: "Thomas Grant (Father)",
    contact: "555-222-3333",
    progress: 40,
  },
  {
    name: "Ethan Gonzalez",
    wish: "To have a gaming computer",
    guardian: "Juan Gonzalez (Father)",
    contact: "555-444-5555",
    progress: 60,
  },
  {
    name: "Natalie Gray",
    wish: "To meet her favorite athlete, Serena Williams",
    guardian: "Megan Gray (Mother)",
    contact: "555-777-8888",
    progress: 90,
  },
  {
    name: "Daisy Ingram",
    wish: "To meet her favorite singer, Taylor Swift",
    guardian: "Robert Ingram (Father)",
    contact: "555-987-6543",
    progress: 25,
  },

  {
    name: "Jacob Ibanez",
    wish: "To visit the Wizarding World of Harry Potter",
    guardian: "Maria Ibanez (Mother)",
    contact: "555-876-5432",
    progress: 70,
  },

  {
    name: "Sophia Irwin",
    wish: "To swim with dolphins",
    guardian: "Andrew Irwin (Father)",
    contact: "555-765-4321",
    progress: 90,
  },

  {
    name: "Mia Ives",
    wish: "To have a backyard treehouse",
    guardian: "Emily Ives (Mother)",
    contact: "555-234-5678",
    progress: 10,
  },

  {
    name: "Oliver Inman",
    wish: "To meet his favorite athlete, LeBron James",
    guardian: "David Inman (Father)",
    contact: "555-345-6789",
    progress: 40,
  },
  {
    name: "Olivia Johnson",
    wish: "To meet her favorite singer",
    guardian: "Sarah Johnson (Mother)",
    contact: "555-123-4567",
    progress: 60,
  },
  {
    name: "Maxwell Johnson",
    wish: "Want to go to a baseball game",
    guardian: "Emily Johnson (Mother)",
    contact: "555-666-7777",
    progress: 89,
  },
  {
    name: "Samantha Johnson",
    wish: "To meet Stephen King",
    guardian: "Michael Johnson (Father)",
    contact: "555-987-6543",
    progress: 80,
  },

  {
    name: "Jacob Jackson",
    wish: "To have a gaming computer",
    guardian: "Emily Jackson (Mother)",
    contact: "555-555-1212",
    progress: 10,
  },

  {
    name: "Olivia James",
    wish: "To go on a Disney cruise",
    guardian: "Sarah James (Aunt)",
    contact: "555-555-5555",
    progress: 30,
  },

  {
    name: "Nathan Jacobs",
    wish: "To attend a professional football game",
    guardian: "Robert Jacobs (Father)",
    contact: "555-123-4567",
    progress: 50,
  },

  {
    name: "Isabella Johnson",
    wish: "To go on a trip to Hawaii",
    guardian: "Laura Johnson (Mother)",
    contact: "555-444-5678",
    progress: 95,
  },

  {
    name: "Alexander Jefferson",
    wish: "To meet his favorite singer, Taylor Swift",
    guardian: "Katie Jefferson (Mother)",
    contact: "555-111-2222",
    progress: 70,
  },
  {
    name: "Lucas Johnson",
    wish: "To have a basketball hoop in his backyard",
    guardian: "Jennifer Johnson (Mother)",
    contact: "555-555-1212",
    progress: 5,
  },

  {
    name: "Grace Jenkins",
    wish: "To go on a shopping spree",
    guardian: "John Jenkins (Father)",
    contact: "555-876-5432",
    progress: 60,
  },
  {
    name: "Lucas Kim",
    wish: "Want to go to the Grand Canyon",
    guardian: "Jin Kim (Father)",
    contact: "555-222-3333",
    progress: 88,
  },
  {
    name: "Ethan Lee",
    wish: "To go on a shopping spree",
    guardian: "Jennifer Lee (Mother)",
    contact: "555-123-4567",
    progress: 50,
  },
  {
    name: "Sarah Lee",
    wish: "Want to go to Japan",
    guardian: "David Lee (Father)",
    contact: "555-123-4567",
    progress: 68,
  },
  {
    name: "Logan Green",
    wish: "To meet a famous athlete",
    guardian: "Laura Green (Mother)",
    contact: "555-123-4567",
    progress: 92,
  },
  {
    name: "Jacob Martinez",
    wish: "To attend a professional basketball game",
    guardian: "Maria Martinez (Mother)",
    contact: "555-123-4567",
    progress: 70,
  },
  {
    name: "Tina Nguyen",
    wish: "Want to meet a famous singer",
    guardian: "Phuong Nguyen (Mother)",
    contact: "555-555-5555",
    progress: 49,
  },
  {
    name: "Jasmine Patel",
    wish: "Want to go on a roller coaster",
    guardian: "Neha Patel (Auntie)",
    contact: "555-888-9999",
    progress: 90,
  },
  {
    name: "Carla Smith",
    wish: "Want to meet a dolphin",
    guardian: "Mark Smith (Father)",
    contact: "555-444-5555",
    progress: 40,
  },
  {
    name: "Avery Scott",
    wish: "To go to a water park",
    guardian: "Michael Scott (Father)",
    contact: "555-123-4567",
    progress: 88,
  },
  {
    name: "Chloe White",
    wish: "To go on a horseback riding adventure",
    guardian: "Rachel White (Mother)",
    contact: "555-123-4567",
    progress: 36,
  },
  {
    name: "Noah Wright",
    wish: "To go on a hot air balloon ride",
    guardian: "Jessica Wright (Mother)",
    contact: "555-123-4567",
    progress: 54,
  },
];

export default cardExamples;
